TEMPLATE = app
QT = gui core
CONFIG += qt release warn_on console
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
LIBS +=
LIBS+=
FORMS = ui/mainwindow.ui
HEADERS = src/qjoystick.h
SOURCES = src/qjoystick.cpp src/main.cpp
